name: CI

on:
  push:
    paths:
      - '.github/workflows/ci.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t ecommerce-ci -f '.github/devcontainer/Dockerfile' .

      - name: Run CI inside container
        run: docker run --rm ecommerce-ci
